version: '3'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
  adminer:
    image: adminer
    ports:
      - "8081:8081"
  app:
    build: .
    environment:
      PG_PASSWORD: ${PG_PASSWORD}
      PG_CONNECTION_STRING: jdbc:postgresql://db:5432/postgres
    volumes:
      - /mnt/42CC6B144201C850/h2db:/app/h2db
    ports:
      - "8080:8080"
    depends_on:
      - db