
application:
  max-range-size-kb: 1024

server:
  port: 8080
  #ssl:
  #  key-store-type: PKCS12
  #  key-store: "classpath:keystore.p12"
  #  key-store-password: 18273645
  #  key-alias: myserver
  #  enabled: true

spring:
  mvc:
    static-path-pattern: /static/**
  content:
    rest:
      base-uri: api
  data:
    rest:
      base-path: api
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_CONNECTION_STRING:jdbc:postgresql:postgres}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect